//TO REQUEST API
export const API_REQUEST='API_REQUEST'



//------------------To show the loading state in UI
export const SHOW_LOADER="SHOW_LOADER"
export const HIDE_LOADER="HIDE_LOADER"

//----------------- To gain the DEVICE UNIQUE ID
export const GET_DEVICE_INFO_START="GET_DEVICE_INFO_START"
export const GET_DEVICE_INFO_SUCCESS="GET_DEVICE_INFO_SUCCESS"
export const GET_DEVICE_INFO_FAIL="GET_DEVICE_INFO_FAIL"
export const INSERT_DEVICE_INFO="INSERT_DEVICE_INFO"




//------------LOGIN PROCESS-----------------------------------
export const LOGIN_START="LOGIN_START"
export const UPDATE_LOGIN_DATA_SUCCESS="UPDATE_LOGIN_DATA"
export const UPDATE_LOGIN_DATA_FAIL="UPDATE_LOGIN_DATA"
export const LOGIN_SUCCESS="LOGIN_SUCCESS"
export const LOGIN_FAIL="LOGIN_FAIL"


//------------EXTERNAL LOGIN PROCESS-----------------------------------
export const EXTERNAL_LOGIN_START="EXTERNAL_LOGIN_START"
export const UPDATE_EXTERNAL_LOGIN_DATA_SUCCESS="UPDATE_EXTERNAL_LOGIN_DATA"
export const UPDATE_EXTERNAL_LOGIN_DATA_FAIL="UPDATE_EXTERNAL_LOGIN_DATA"
export const EXTERNAL_LOGIN_SUCCESS="EXTERNAL_LOGIN_SUCCESS"
export const EXTERNAL_LOGIN_FAIL="EXTERNAL_LOGIN_FAIL"




//----------LOGOUT PROCESS-----------------------------------
export const LOGOUT_START="LOGOUT_START"
export const REMOVE_ACCESS_TOKEN="REMOVE_ACCESS_TOKEN"
export const LOGOUT_SUCCESS="LOGOUT_SUCCESS"
export const LOGOUT_FAIL="LOGOUT_FAIL"


//-----------Forgot Password---------------------------------
export const FORGOT_PASSWORD_START="FORGOT_PASSWORD_START"
export const UPDATE_FORGOT_DATA="UPDATE_FORGOT_DATA"
export const FORGOT_PASSWORD_SUCCESS="FORGOT_PASSWORD_SUCCESS"
export const FORGOT_PASSWORD_FAIL="FORGOT_PASSWORD_FAIL"


//-----------Reset Password---------------------------------
export const RESET_PASSWORD_START="RESET_PASSWORD_START"
export const UPDATE_RESET_DATA="UPDATE_RESET_DATA"
export const RESET_PASSWORD_SUCCESS="RESET_PASSWORD_SUCCESS"
export const RESET_PASSWORD_FAIL="RESET_PASSWORD_FAIL"



//-------------Registration-------------------------------
export const REGISTRATION_START="REGISTRATION_START"
export const UPDATE_REGISTRATION_DATA_SUCCESS="UPDATE_REGISTRATION_DATA_SUCCESS"
export const UPDATE_REGISTRATION_DATA_FAIL="UPDATE_REGISTRATION_DATA_FAIL"
export const REGISTRATION_FAIL="REGISTRATION_FAIL"
export const REGISTRATION_SUCCESS="REGISTRATION_SUCCESS"

//------------------User----------------------------------
export const GET_USER_START="GET_USER_START"
export const GET_USER_SUCCESS="GET_USER_SUCCESS"
export const UPDATE_GET_USER_DATA_SUCCESS="UPDATE_GET_USER_DATA"
export const UPDATE_GET_USER_DATA_FAIL="UPDATE_GET_USER_DATA"
export const GET_USER_FAIL="GET_USER_FAIL"

export const UPDATE_USER_START="UPDATE_USER_START"
export const UPDATE_USER_SUCCESS="UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAIL="UPDATE_USER_FAIL"
export const UPDATE_UPDATE_USER_DATA_SUCCESS="UPDATE_UPDATE_USER_DATA"
export const UPDATE_UPDATE_USER_DATA_FAIL="UPDATE_UPDATE_USER_DATA"

//-------------------MEDICAL PROFILE-----------------------
export const GET_ALL_MEDICAL_PROFILES_START="GET_ALL_MEDICAL_PROFILES_START"
export const GET_ALL_MEDICAL_PROFILES_SUCCESS="GET_ALL_MEDICAL_PROFILES_SUCCESS"
export const GET_ALL_MEDICAL_PROFILES_FAIL="GET_ALL_MEDICAL_PROFILES_FAIL"
export const GET_ALL_MEDICAL_PROFILES_DATA_SUCCESS="GET_ALL_MEDICAL_PROFILES_DATA_SUCCESS"
export const GET_ALL_MEDICAL_PROFILES_DATA_FAIL="GET_ALL_MEDICAL_PROFILES_DATA_FAIL"

export const GET_USER_MEDICAL_PROFILES_START="GET_USER_MEDICAL_PROFILES_START"
export const GET_USER_MEDICAL_PROFILES_SUCCESS="GET_USER_MEDICAL_PROFILES_SUCCESS"
export const GET_USER_MEDICAL_PROFILES_FAIL="GET_USER_MEDICAL_PROFILES_FAIL"
export const GET_USER_MEDICAL_PROFILES_DATA_SUCCESS="GET_USER_MEDICAL_PROFILES_DATA_SUCCESS"
export const GET_USER_MEDICAL_PROFILES_DATA_FAIL="GET_USER_MEDICAL_PROFILES_DATA_FAIL"

export const CREATE_MEDICAL_PROFILE_START="CREATE_MEDICAL_PROFILE_START"
export const CREATE_MEDICAL_PROFILE_SUCCESS="CREATE_MEDICAL_PROFILE_SUCCESS"
export const CREATE_MEDICAL_PROFILE_FAIL="CREATE_MEDICAL_PROFILE_FAIL"

export const UPDATE_MEDICAL_PROFILE_START="UPDATE_MEDICAL_PROFILE_START"
export const UPDATE_MEDICAL_PROFILE_SUCCESS="UPDATE_MEDICAL_PROFILE_SUCCESS"
export const UPDATE_MEDICAL_PROFILE_FAIL="UPDATE_MEDICAL_PROFILE_FAIL"

export const DELETE_MEDICAL_PROFILE_START="DELETE_MEDICAL_PROFILE_START"
export const DELETE_MEDICAL_PROFILE_SUCCESS="DELETE_MEDICAL_PROFILE_SUCCCESS"
export const DELETE_MEDICAL_PROFILE_FAIL="DELETE_MEDICAL_PROFILE_FAIL"

//-------------------MEDICAL RECORDS-----------------------
export const GET_ALL_MEDICAL_RECORDS_START="GET_ALL_MEDICAL_RECORDS_START"
export const GET_ALL_MEDICAL_RECORDS_SUCCESS="GET_ALL_MEDICAL_RECORDS_SUCCESS"
export const GET_ALL_MEDICAL_RECORDS_FAIL="GET_ALL_MEDICAL_RECORDS_FAIL"
export const GET_ALL_MEDICAL_RECORDS_DATA_SUCCESS="GET_ALL_MEDICAL_RECORDS_DATA_SUCCESS"
export const GET_ALL_MEDICAL_RECORDS_DATA_FAIL="GET_ALL_MEDICAL_RECORDS_DATA_FAIL"

export const GET_USER_MEDICAL_RECORDS_START="GET_USER_MEDICAL_RECORDS_START"
export const GET_USER_MEDICAL_RECORDS_SUCCESS="GET_USER_MEDICAL_RECORDS_SUCCESS"
export const GET_USER_MEDICAL_RECORDS_FAIL="GET_USER_MEDICAL_RECORDS_FAIL"
export const GET_USER_MEDICAL_RECORDS_DATA_SUCCESS="GET_USER_MEDICAL_RECORDS_DATA_SUCCESS"
export const GET_USER_MEDICAL_RECORDS_DATA_FAIL="GET_USER_MEDICAL_RECORDS_DATA_FAIL"

export const CREATE_MEDICAL_RECORD_START="CREATE_MEDICAL_RECORD_START"
export const CREATE_MEDICAL_RECORD_SUCCESS="CREATE_MEDICAL_RECORD_SUCCESS"
export const CREATE_MEDICAL_RECORD_FAIL="CREATE_MEDICAL_RECORD_FAIL"

export const UPDATE_MEDICAL_RECORD_START="UPDATE_MEDICAL_RECORD_START"
export const UPDATE_MEDICAL_RECORD_SUCCESS="UPDATE_MEDICAL_RECORD_SUCCESS"
export const UPDATE_MEDICAL_RECORD_FAIL="UPDATE_MEDICAL_RECORD_FAIL"

export const DELETE_MEDICAL_RECORD_START="DELETE_MEDICAL_RECORD_START"
export const DELETE_MEDICAL_RECORD_SUCCESS="DELETE_MEDICAL_RECORD_SUCCCESS"
export const DELETE_MEDICAL_RECORD_FAIL="DELETE_MEDICAL_RECORD_FAIL"


//---------------------Family Members-------------------------------------
export const GET_ALL_FAMILY_MEMBERS_START="GET_ALL_FAMILY_MEMBERS_START"
export const GET_ALL_FAMILY_MEMBERS_SUCCESS="GET_ALL_FAMILY_MEMBERS_SUCCESS"
export const GET_ALL_FAMILY_MEMBERS_FAIL="GET_ALL_FAMILY_MEMBERS_FAIL"
export const GET_ALL_FAMILY_MEMBERS_DATA_SUCCESS="GET_ALL_FAMILY_MEMBERS_DATA_SUCCESS"
export const GET_ALL_FAMILY_MEMBERS_DATA_FAIL="GET_ALL_FAMILY_MEMBERS_DATA_FAIL"

export const CREATE_FAMILY_MEMBER_START="CREATE_FAMILY_MEMBER_START"
export const CREATE_FAMILY_MEMBER_SUCCESS="CREATE_FAMILY_MEMBER_SUCCESS"
export const CREATE_FAMILY_MEMBER_FAIL="CREATE_FAMILY_MEMBER_FAIL"
export const CREATE_FAMILY_MEMBERS_DATA_SUCCESS="GET_ALL_FAMILY_MEMBERS_DATA_SUCCESS"
export const CREATE_FAMILY_MEMBERS_DATA_FAIL="GET_ALL_FAMILY_MEMBERS_DATA_FAIL"